### ISSUE TITLE
Causes a crash on 1.14.4

### ISSUE THREAD

**Issue by sepsol** [ArtixAllMighty/JustFashion#5]
After the singleplayer world is loaded, it performs a 'saving world...' (just like when you want to close the game and get out of the world) and then the game just fully stops working and quits. Here's the full list of what I have on my game:

**GAME VERSION**
Minecraft 1.14.4

**FML VERSION**
Forge 28.1.0

**OPTIFINE VERSION**
HD U F4 pre9
_*Because the final stable version didn't allow me to launch the game for now*_

**MODS**
Advanced Skin Customization 2.0.2
Better Animals 5.2.1
Camera 1.4.8
Carry On 1.12.3
Crafting Station 2.0.2
Create 0.1.1
Enchantment Descriptions 1.3.3
Filters 1.0.0
Free Look 1.3.1
Go Prone 1.0.3
HWYLA 1.10.6-B67
JEI 6.0.0.11
JustFashion 2.1.0.1
MineMenu 1.8.2
Shoulder Surfing 1.20
Sit 1.1.3
Smooth Scrolling Everywhere 1.1
SubLib 2.0.1.0
Trash Slot 10.4.7
Tree Choppin 1.2.0
WorldEdit 7.0.1
WorldHandler 2.6.4

**SHADERPACKS**
Sildurs Enhanced Default 1.09
Sildurs Vibrant Shaders 1.23 (any version)
SEUS 11.0
SEUS Renewed 1.0.0
_*None of these were loaded in time of crash*_

**RESOURCEPACKS**
JustFashion Resource Pack (only this one was on)
Faithful (any version)
VanillaBDcraft (any version)
_*None of these were loaded in time of crash*_

**Comment by sepsol** [comment]
**UPDATE**
I even removed the 'Advanced Skin Customization' and the game still crashed.

**Comment by sepsol** [comment]
**UPDATE 2**
Ok so I did some more testing and I turned off my mods (including OptiFine), shaders, and resourcepacks. This time I was able to get into my world, but as soon as I pressed the 'wardrobe' key the world suddenly saved and the game was closed. Hope this helps.

**Comment by AbsolemJackdaw** [comment]
the biggest thing that is going to help me here is a log...
find it in your miencraft install directory under the folder 'logs'

**Comment by AbsolemJackdaw** [comment]
also, just in case, do you have the resourcepack installed ?

**Comment by sepsol** [comment]
Yes I do, here's the log you requested: [DOWNLOAD LINK](https://www.dropbox.com/s/xqtqtoxvl48c8nx/2019-10-15-1.log.gz?dl=1)

**Comment by AbsolemJackdaw** [comment]
Did you download the resource pack ? Have tou tried adding one yourself ? 
Did you fiddle with the reaourcepack ? 
It looks like a rp issue. 
Ill look from my side. Any info can help.
Try and see if you ca  fi d any discrepensies in yohr resourcepack too !

**Comment by sepsol** [comment]
I downloaded your resourcepack and enabled it. After encountering several crashes, I decided to turn off all the mods (including OptiFine), shaders and resourcepacks. I only left on the SubLib and JustFashion mod and its resourcepack.

I didn't fiddle with the resourcepack whatsoever. But to be honest my first run went like this:

I downloaded everything, I copied everything to their respective folders, then created a new SP world for testing purposes, jumped right in, pressed 'w' to move forward and the game crashed. So:

a) I forgot to turn on the resourcepack inside the game for the first time

b) I didn't know that 'w' was going to open the 'wardrobe' and I pressed it (which caused the crash)

At first I looked at my mods and thought there was something wrong with my mods, I should turn off the ones that mess with my player model. So I turned off the 'Advanced Skin Customization' mod and the game still crashed.

After that I disabled everything and you know the results I got. That is all that happened.

**Comment by sepsol** [comment]
Maybe the first run screwed everything up?!

**Comment by sepsol** [comment]
Also the log I sent you was probably not for my very first run.

**Comment by SepSol** [comment]
Also the log I sent you was probably not for my very first run.

**Comment by AbsolemJackdaw** [comment]
It shouldnt matter. No other mod was interfering.
Apperantly the syntax in one of tye json files is wrong. But im pretty sure ut might rather be how its read.
 Anyway, ill throw myself in the issue when i can !

**Comment by sepsol** [comment]
Thank you so much!

**Comment by sepsol** [comment]
So today I decided that I want to try this again, and this is what I've got:
[debug.log](https://github.com/ArtixAllMighty/JustFashion/files/3739986/debug.log)
[latest.log](https://github.com/ArtixAllMighty/JustFashion/files/3739987/latest.log)

And this is my mods:
![image](https://user-images.githubusercontent.com/47871887/67021791-060e9a80-f10d-11e9-9694-4fc6ca3aac65.png)

And the texture was enabled.

**Comment by AbsolemJackdaw** [comment]
oh hey

[17Oct2019 18:33:30.295] [Client thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: java.lang.NoSuchFieldException: layerRenderers

this is an issue i resolved in the past. are you using the latest release ?

**Comment by AbsolemJackdaw** [comment]
this is basically a copy of #2

**Comment by AbsolemJackdaw** [comment]
could you try forge 28.0.81 for me ?  
the mod was coded under that version and it _could_ be a quick solution. 
if thats not the case then im puzzled and i'll look for a permanent solution

**Comment by sepsol** [comment]
Ok, so I checked and my mod is updated to the latest. I tried with Forge 28.0.81 and the game still crashed. Here's the log (Is the debug useful?):

[latest.log](https://github.com/ArtixAllMighty/JustFashion/files/3746625/latest.log)
[debug.log](https://github.com/ArtixAllMighty/JustFashion/files/3746626/debug.log)


Minecraft 1.14.4
Forge 28.0.81
SubLib 2.0.1.0
JustFashion 2.1.0.1

And I only loaded your recourcepack:
Fashion Base Pack for 1.14.4

No shaders and OptiFine.

**Comment by AbsolemJackdaw** [comment]
![image](https://user-images.githubusercontent.com/3628535/67145761-6411be00-f284-11e9-8add-f3166adac5df.png)
 ?

**Comment by AbsolemJackdaw** [comment]
well, shouldnt matter, the error stays the same


net.minecraftforge.fml.common.ObfuscationReflectionHelper$UnableToFindFieldException: java.lang.NoSuchFieldException: layerRenderers

this is weird.
ill see what i can do

**Comment by sepsol** [comment]
Thanks

**Comment by Trikzon** [comment]
This may be the same problem, but I have a crash report and it seems to be it

> UnableToFindFieldException: java.lang.NoSuchFieldException: layerRenderers

Forge Version: forge-28.1.61 (1.14.4)
Just Fashion Version: fashion-JustFashion-1.14.4-2.1.0.1
SubLib Version: subcommonlib-1.14.4-2.0.1.0

**Comment by Trikzon** [comment]
Forgot the link
https://gist.github.com/Trikzon/b899eb01ea93cfeb47dafa59c6577866

**Comment by sepsol** [comment]
It works now, thanks :)
